apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=mysqlkube
resources:
  - efs-provisioner.yml
  - rbac.yml
  - mysql-deployment.yml
  - wordpress-deployment.yml